### ISSUE TITLE
Error thrown in couldnot execute ImageMagick "identify"

### ISSUE THREAD

**Issue by sudheesh001** [martinheidegger/mapslice#16]
```
C:\Users\susingan\Desktop\MapSlice>mapslice -f a_base.png

Error: Error#2: Error while fetching size of File: a_base.png; Error: Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "a_base.png" this most likely means the gm/convert binaries can't be found
    at MapSlicer.<anonymous> (C:\Users\susingan\AppData\Roaming\npm\node_modules\mapslice\lib\MapSlicer.js:79:40)
    at emitMany (events.js:127:13)
    at gm.emit (events.js:201:7)
    at gm.<anonymous> (C:\Users\susingan\AppData\Roaming\npm\node_modules\mapslice\node_modules\gm\lib\getters.js:70:16)
    at cb (C:\Users\susingan\AppData\Roaming\npm\node_modules\mapslice\node_modules\gm\lib\command.js:322:16)
    at ChildProcess.<anonymous> (C:\Users\susingan\AppData\Roaming\npm\node_modules\mapslice\node_modules\gm\lib\command.js:232:9)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at ChildProcess.cp.emit (C:\Users\susingan\AppData\Roaming\npm\node_modules\mapslice\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

C:\Users\susingan\Desktop\MapSlice>identify -ping -format %wx%h a_base.png
5120x2880
C:\Users\susingan\Desktop\MapSlice>
```
The binary command `identify -ping -format %wx%h a_base.png` which is throwing the error is accessible and gives the result as `5120x2880` but map slice fails

**Comment by martinheidegger** [comment]
I am not sure off the top of my hat but...

- It looks for the `gm` command and not the `identify` command. After installing `gm` it should be available in the command line
- `identify` is a `ImageMagick` command. Maybe the `-i ` option (to use `imageMagick` does the trick.

**Comment by sudheesh001** [comment]
Yes installing `gm` fixes the issue but isn't only one of IM/GM needed ?
Yes adding the `-i` seems to do the trick.
