### ISSUE TITLE
Error: invalid options argument

### ISSUE THREAD

**Issue by sebastianbk** [martinheidegger/mapslice#22]
Hi,

I've installed mapslice using npm but, whenever I try to run it, I get an error from the `mkdirp` dependency saying: `invalid options argument`

You can see the output below.

What am I doing wrong?

```
$ mapslice -f highres.jpeg
Input File: highres.jpeg
Input Size: 5047x2794
Level #0: 256x256, 157x87
Level #1: 512x512, 314x174
Level #2: 1024x1024, 628x348
Level #3: 2048x2048, 1256x696
Level #4: 4096x4096, 2512x1392
Level #5: 8192x8192, 5024x2784
Single Tile Size: 256x256px
Files to process: 1371
Progress:                       ▏0% ▏0/1371 ▏/usr/local/lib/node_modules/mapslice/node_modules/mkdirp/lib/opts-arg.js:13
    throw new TypeError('invalid options argument')
    ^

TypeError: invalid options argument
    at optsArg (/usr/local/lib/node_modules/mapslice/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/usr/local/lib/node_modules/mapslice/node_modules/mkdirp/index.js:11:10)
    at processLevel (/usr/local/lib/node_modules/mapslice/lib/processLevel.js:7:3)
    at /usr/local/lib/node_modules/mapslice/lib/MapSlicer.js:78:13
    at /usr/local/lib/node_modules/mapslice/node_modules/async/dist/async.js:2948:28
    at replenish (/usr/local/lib/node_modules/mapslice/node_modules/async/dist/async.js:440:21)
    at /usr/local/lib/node_modules/mapslice/node_modules/async/dist/async.js:445:13
    at eachOfLimit$1 (/usr/local/lib/node_modules/mapslice/node_modules/async/dist/async.js:471:34)
    at awaitable (/usr/local/lib/node_modules/mapslice/node_modules/async/dist/async.js:208:32)
    at eachOfSeries (/usr/local/lib/node_modules/mapslice/node_modules/async/dist/async.js:658:16)
```

**Comment by martinheidegger** [comment]
Hello @sebastianbk 

Thank you for reporting this issue, it seems I havn't had tests added to make sure that the folders were properly created. I updated the use of mkdirp and it should be working now. Published as version 2.0.2
