### ISSUE TITLE
Error fetching size of file and em identify not returning a file

### ISSUE THREAD

**Issue by beshad** [martinheidegger/mapslice#23]
i just installed this library on Frdora and whether i use the global mapslice install via terminal or run or via Node similar to the sample code provided in the doc i get these errors:

```
$ node index.js 
Error: Error while fetching size of file
    at gm.<anonymous> (/var/www/sandbox/map/node_modules/mapslice/lib/getImageSize.js:15:33)
    at gm.emit (events.js:311:20)
    at gm.<anonymous> (/var/www/sandbox/map/node_modules/gm/lib/getters.js:129:14)
    at cb (/var/www/sandbox/map/node_modules/gm/lib/command.js:322:16)
    at ChildProcess.onExit (/var/www/sandbox/map/node_modules/gm/lib/command.js:305:9)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12) {
  code: 'MMAPIDENT',
  cause: Error: Command failed: gm identify: No decode delegate for this image format (/var/www/sandbox/map/map.jpg).
  gm identify: Request did not return an image.
  
      at ChildProcess.onExit (/var/www/sandbox/map/node_modules/gm/lib/command.js:301:17)
      at ChildProcess.emit (events.js:311:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:311:20)
      at Pipe.<anonymous> (net.js:668:12) {
    code: 1,
    signal: null
  },
  file: '/var/www/sandbox/map/map.jpg',
  hint: undefined
}
```
or

```
mapslice -f map.jpg 

Error: Error while fetching size of file
---
code: MMAPIDENT
cause: Error: Command failed: gm identify: No decode delegate for this image format (map.jpg).
gm identify: Request did not return an image.

file: map.jpg

```

the map.jpg is a valid jpeg file and i have installed 'GraphicsMagick' but don't have imagicmagick. any idea why these errors?

thanks

**Comment by martinheidegger** [comment]
Hello @beshad, thank you for reporting this problem. For figuring out what is wrong it would be good to know the graphicsmagick version you are running.

Maybe you could also try to run `$ gm identify /var/www/sandbox/map/map.jpg` to see if that works in your command line, as it is pretty much what is executed by mapslice.

**Comment by beshad** [comment]
> Hello @beshad, thank you for reporting this problem. For figuring out what is wrong it would be good to know the graphicsmagick version you are running.
> 
> Maybe you could also try to run `$ gm identify /var/www/sandbox/map/map.jpg` to see if that works in your command line, as it is pretty much what is executed by mapslice.
> 
> _Note: I tested your example at https://github.com/beshad/map-slicer-example and it worked fine for me on my mac. Maybe you have a incompatible `gm` version?_

thanks for the help, i tried my other macos device and after running `gm identify /var/www/sandbox/map/map.jpg` it turned out that i had not have installed the gm properly, using brew reinstalled both imagemagick and graphicmagick all worked like a charm, now that i know the problem i will do the same tonight on my Fedora unit. 

awesome library and is exactly what i need to slice images working with Leaflet maps. 

thanks again for the support, i close this issue now
