### ISSUE TITLE
source is not defined

### ISSUE THREAD

**Issue by markios** [martinheidegger/mapslice#7]
I used this package as instructed and I got sourc is not defined at on line 23. I have ImageMagick installed globally.

**Comment by martinheidegger** [comment]
Can you provide the full stack trace?

**Comment by markios** [comment]
.../node_modules/mapslice/lib/MapSlicer.js:23
        return new MapSlicer(source, height, color);

**Comment by markios** [comment]
ReferenceError: source is not defined
    at MapSlicer (/Users/markkellett/Projects/zeebox/openbox-au/scripts/clients/beamshot/node_modules/mapslice/lib/MapSlicer.js:23:30)
    at createBigShot (/Users/markkellett/Projects/zeebox/openbox-au/scripts/clients/beamshot/lib/upload.js:124:21)
    at /Users/markkellett/Projects/zeebox/openbox-au/scripts/clients/beamshot/lib/upload.js:160:9
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

**Comment by martinheidegger** [comment]
Thank you for posting this bug! Stupid mistake, sorry for that :bow: You probably wrote something like

```JavaScript
MapSlicer(...)
```
if you rewrite it to 
```JavaScript
new MapSlicer(...)
```
then it should work right now.

**Comment by martinheidegger** [comment]
Just found a bug, please wait with updating.

**Comment by martinheidegger** [comment]
Alright: I updated and published the code (v1.0.2). (I added even a few unit tests, wee, about time :) ).
Please note that I changed the API slightly. You now should call `.start()` to start the mapslicing.
